services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      DB_URL: jdbc:postgresql://db:5432/lfk
      DB_USERNAME: postgres
      DB_PASSWORD: root
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: lfk
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: