spring:
  application:
    name: vr-back
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
      platform: postgres

logging:
  level:
    org.springframework.core.convert: DEBUG
    org.springframework.web: DEBUG

server:
  port: 80